### ISSUE TITLE
Cannot start main.py

### ISSUE THREAD

**Issue by Mattallmighty** [not-matt/Systematic-LEDs#20]
I have taken the latest master pull and having errors when I start main.py. It starts for a second then the following errors come up. 

```
audio-reactive-led-strip) C:\Systematic-LEDs-master\python>python main.py
Traceback (most recent call last):
  File "C:\Systematic-LEDs-master\python\lib\microphone.py", line 21, in start_stream
    callback(y)
  File "main.py", line 1353, in microphone_update
    boards[board].show(outputs[board])
  File "C:\Systematic-LEDs-master\python\lib\devices.py", line 145, in show
    self._sock.sendto(message, (self._ip, self._port))
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1437, in <module>
    microphone.start_stream(microphone_update)
  File "C:\Systematic-LEDs-master\python\lib\microphone.py", line 27, in start_stream
    gui.label_error.setText('Audio buffer has overflowed {} times'.format(overflows))
NameError: name 'gui' is not defined

(audio-reactive-led-strip) C:\Systematic-LEDs-master\python>
```
List of my enviroment: 
```
(audio-reactive-led-strip) C:\Systematic-LEDs-master\python>conda list
# packages in environment at C:\Users\Matt\Anaconda3\envs\audio-reactive-led-strip:
#
# Name                    Version                   Build  Channel
ca-certificates           2017.08.26           h94faf87_0
certifi                   2018.1.18                py36_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
intel-openmp              2018.0.0             hd92c6cd_8
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.34               h79bbb47_0
mkl                       2018.0.1             h2108138_4
numpy                     1.14.1           py36hb69e940_2
openssl                   1.0.2n               h74b6da3_0
pip                       9.0.1            py36h226ae91_4
PyAudio                   0.2.11                    <pip>
pyqt                      5.6.0            py36hb5ed885_5
pyqtgraph                 0.10.0                   py36_0
python                    3.6.4                h6538335_1
qt                        5.6.2           vc14h6f8c307_12
scipy                     1.0.0            py36h1260518_0
setuptools                38.5.1                   py36_0
sip                       4.18.1           py36h9c25514_2
sqlite                    3.22.0               h9d3ae62_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wheel                     0.30.0           py36h6c3ec14_1
wincertstore              0.2              py36h7fe50ca_0
zlib                      1.2.11               h8395fce_2

(audio-reactive-led-strip) C:\Systematic-LEDs-master\python>
```
Above using Windows 10 - 64 bit - Python 3.6.4
Downloaded it again on a different windows 10 PC with Python 3.6.2
Guessing because of Python 3.6?

**Comment by kanapoutz78** [comment]
I'm running it perfectly with python 3.6.3 Anaconda (64 bits) so seems to be something else...

**Comment by ahodges9** [comment]
Did you update the IP in config.py? It's failing to resolve the address..

**Comment by Mattallmighty** [comment]
Ah silly me, yes, I have not updated config.py in the folder lib, was going all through main.py code looking for where to configure this. 
I will make a draft guide, say a weeks time @not-matt
