### ISSUE TITLE
OPC problem

### ISSUE THREAD

**Issue by charlieali** [not-matt/Systematic-LEDs#23]
When I try to run main.py i get this error indicating I install opc

runfile('C:/Users/charlie/Desktop/Systematic-LEDs-masterFC/python/main.py', wdir='C:/Users/charlie/Desktop/Systematic-LEDs-masterFC/python')
C:\Users\charlie\Anaconda3\envs\fc3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Unable to import audioled.opc library
You can install this library with `pip install opc`
Traceback (most recent call last):

  File "<ipython-input-1-ab5cfa311b9a>", line 1, in <module>
    runfile('C:/Users/charlie/Desktop/Systematic-LEDs-masterFC/python/main.py', wdir='C:/Users/charlie/Desktop/Systematic-LEDs-masterFC/python')

  File "C:\Users\charlie\Anaconda3\envs\fc3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\charlie\Anaconda3\envs\fc3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/charlie/Desktop/Systematic-LEDs-masterFC/python/main.py", line 1407, in <module>
    server=config.settings["devices"][board]["configuration"]["SERVER"])

  File "C:\Users\charlie\Desktop\Systematic-LEDs-masterFC\python\lib\devices.py", line 162, in __init__
    raise e

  File "C:\Users\charlie\Desktop\Systematic-LEDs-masterFC\python\lib\devices.py", line 158, in __init__
    import audioled.opc

ImportError: No module named 'audioled'
----------------------------------

Only problem Is I already have OPC installed in the environment. I tried uninstalling it and reinstalling and it didn't work.

**Comment by charlieali** [comment]
Solution is actually to uninstall opc, this is trying to call a file. Also opc.py has to be moved to a folder called audioled in the python folder for this to work.
