### ISSUE TITLE
Crash on Win10

### ISSUE THREAD

**Issue by nhmann** [not-matt/Systematic-LEDs#27]
Currently I'm running it on Windows 10 with Anaconda. Python Version is 3.6.4.
I've installed numpy, scipy, pyqtgraph and pyaudio

When I'm running the main.py the window opens for like 2 seconds and then closes.

The console:

(a) C:\Users\NilsH\Desktop\Systematic-LEDs-master\python>python main.py
Traceback (most recent call last):
  File "C:\Users\NilsH\Desktop\Systematic-LEDs-master\python\lib\microphone.py", line 34, in start_stream
    callback(y)
  File "main.py", line 1353, in microphone_update
    boards[board].show(outputs[board])
  File "C:\Users\NilsH\Desktop\Systematic-LEDs-master\python\lib\devices.py", line 145, in show
    self._sock.sendto(message, (self._ip, self._port))
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1437, in <module>
    microphone.start_stream(microphone_update)
  File "C:\Users\NilsH\Desktop\Systematic-LEDs-master\python\lib\microphone.py", line 40, in start_stream
    gui.label_error.setText('Audio buffer has overflowed {} times'.format(overflows))
NameError: name 'gui' is not defined

**Comment by nhmann** [comment]
Nethermind. I forgot to add the IP in the main.py
