### ISSUE TITLE
Unable to open Main.py

### ISSUE THREAD

**Issue by KavTV** [not-matt/Systematic-LEDs#56]
I get this error when trying to launch in anaconda enviroment. Followed the video, keep getting this error.
Could not find settings.ini
No user colours found
No user gradients found
Traceback (most recent call last):
  File "C:\Users\kaspe\Documents\Python Scripts\Systematic-LEDs-master\python\main.py", line 2046, in <module>
    microphone = Microphone(microphone_update)
  File "C:\Users\kaspe\Documents\Python Scripts\Systematic-LEDs-master\python\main.py", line 842, in __init__
    device_info = py_audio.get_device_info_by_host_api_device_index(0,i)
  File "C:\Users\kaspe\Anaconda3\lib\site-packages\pyaudio.py", line 852, in get_device_info_by_host_api_device_index
    host_api_device_index)
OSError: [Errno -9996] Invalid device

**Comment by StanglAndreas** [comment]
Hi i got the same error with python 3.7
try python 3.6

**Comment by KavTV** [comment]
Changed to python 3.6, working great
